### ISSUE TITLE
Clarify the minimal setup and what that gets user; versus additional steps to get additional data

### ISSUE THREAD

**Issue by yunzhouMSFT** [Microsoft/AppInsights-iOS#13]
It would be great if the instructions are clearer on what’s the minimal setup to get some default data (page views/sessions/users) to show up in the portal, and then in addition what else the user can set up (custom telemetry, for example) to get more than that.
o	Currently, it’s not clear at which step the data will show up.

**Comment by lukasspiess** [comment]
Added some additional info on this in 2282e0dfaf535055e8c30e7f76bbf2a1cb1c606c
