### ISSUE TITLE
Swift: in Step 5, the IDE recommends removing “message:” from the code snippet. 

### ISSUE THREAD

**Issue by yunzhouMSFT** [Microsoft/AppInsights-iOS#18]
For Swift, in Step 5, the IDE recommends removing “message:” from the code snippet. Should just be:
		MSAIMetricsManager.trackTraceWithMessage("Test message");

**Comment by lukasspiess** [comment]
Fixed in 2282e0dfaf535055e8c30e7f76bbf2a1cb1c606c
