### ISSUE TITLE
In the Download & Extract section, wording for Step 3 is a little awkward with use of “we” 

### ISSUE THREAD

**Issue by yunzhouMSFT** [Microsoft/AppInsights-iOS#20]
In the Download & Extract section, wording for Step 3 is a little awkward with use of “we”. 
o	Instead of “we usually put 3rd-party code… , so we move the directory…”, how about “You can move the folder to anywhere in your project director and it will work. But to keep code organized, you can also create a Vendor subdirectory and put the folder there”.

**Comment by lukasspiess** [comment]
Fixed in 06e130abbe50c20353524171a8e88a43a58c47cb
