### ISSUE TITLE
Add switch to turn off auto pageView tracking

### ISSUE THREAD

**Issue by lukasspiess** [Microsoft/AppInsights-iOS#22]
We should definitely have a master switch for this feature.

**Comment by lukasspiess** [comment]
@chrwend Do you want to look into that?

**Comment by chrwend** [comment]
it would be a pleasure, my friend.

Von meinem iPhone gesendet

Am 03.03.2015 um 23:38 schrieb Lukas Spieß <notifications@github.com<mailto:notifications@github.com>>:


@chrwend<https://github.com/chrwend> Do you want to look into that?

**Comment by lukasspiess** [comment]
Will be closed in #28
